# syntax=docker/dockerfile:1

# ---- Base ----------------------------------------------------------------
# Use a slim Node image. Node 22 is the current Active LTS.
FROM node:22-alpine AS base
# libc6-compat helps some native deps run on Alpine.
RUN apk add --no-cache libc6-compat
# Enable pnpm via corepack (version comes from package.json "packageManager" if set).
RUN corepack enable
WORKDIR /app

# ---- Dependencies --------------------------------------------------------
# Install dependencies separately so this layer is cached unless lockfile changes.
FROM base AS deps
COPY package.json pnpm-lock.yaml ./
RUN --mount=type=cache,id=pnpm,target=/root/.local/share/pnpm/store \
    pnpm install --frozen-lockfile

# ---- Builder -------------------------------------------------------------
FROM base AS builder
COPY --from=deps /app/node_modules ./node_modules
COPY . .
# Disable Next.js telemetry during the build.
ENV NEXT_TELEMETRY_DISABLED=1
RUN pnpm build

# ---- Runner --------------------------------------------------------------
# Minimal final image that only contains the standalone server output.
FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Run as a non-root user for security.
RUN addgroup --system --gid 1001 nodejs \
  && adduser --system --uid 1001 nextjs

# Copy the public assets and the standalone server output produced by `output: "standalone"`.
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# server.js is generated by the standalone build.
CMD ["node", "server.js"]
